version: "3.1"
services:
  db:
    image: postgres
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
